C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\simple_shader.vert -o shaders\simple_shader.vert.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\simple_shader.frag -o shaders\simple_shader.frag.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\point_light.vert -o shaders\point_light.vert.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\point_light.frag -o shaders\point_light.frag.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\gourard_shader.vert -o shaders\gourard_shader.vert.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\gourard_shader.frag -o shaders\gourard_shader.frag.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\flat_shader.vert -o shaders\flat_shader.vert.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\flat_shader.frag -o shaders\flat_shader.frag.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\mv_simple_shader.vert -o shaders\mv_simple_shader.vert.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\mv_simple_shader.frag -o shaders\mv_simple_shader.frag.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\mv_gourard_shader.vert -o shaders\mv_gourard_shader.vert.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\mv_gourard_shader.frag -o shaders\mv_gourard_shader.frag.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\mv_flat_shader.vert -o shaders\mv_flat_shader.vert.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\mv_flat_shader.frag -o shaders\mv_flat_shader.frag.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\wd_simple_shader.vert -o shaders\wd_simple_shader.vert.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\wd_simple_shader.frag -o shaders\wd_simple_shader.frag.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\wd_gourard_shader.vert -o shaders\wd_gourard_shader.vert.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\wd_gourard_shader.frag -o shaders\wd_gourard_shader.frag.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\wd_flat_shader.vert -o shaders\wd_flat_shader.vert.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\wd_flat_shader.frag -o shaders\wd_flat_shader.frag.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\no_txt_phong_shader.vert -o shaders\no_txt_phong_shader.vert.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\no_txt_phong_shader.frag -o shaders\no_txt_phong_shader.frag.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\no_txt_gourard_shader.vert -o shaders\no_txt_gourard_shader.vert.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\no_txt_gourard_shader.frag -o shaders\no_txt_gourard_shader.frag.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\no_txt_flat_shader.vert -o shaders\no_txt_flat_shader.vert.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\no_txt_flat_shader.frag -o shaders\no_txt_flat_shader.frag.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\mrb_phong_shader.vert -o shaders\mrb_phong_shader.vert.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\mrb_phong_shader.frag -o shaders\mrb_phong_shader.frag.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\mrb_gourard_shader.vert -o shaders\mrb_gourard_shader.vert.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\mrb_gourard_shader.frag -o shaders\mrb_gourard_shader.frag.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\mrb_flat_shader.vert -o shaders\mrb_flat_shader.vert.spv
C:\VulkanSDK\1.3.268.0\Bin\glslc.exe shaders\mrb_flat_shader.frag -o shaders\mrb_flat_shader.frag.spv
pause